### ISSUE TITLE
Puu_Black.xml needs to be (re)labeled completely

### ISSUE THREAD

**Issue by Enlight1** [CaveStoryModdingCommunity/FreewareHacks#3]
[Puu_Black.xml](https://github.com/CaveStoryModdingCommunity/FreewareHacks/blob/unsorted-dump/XML%20(BL%20Hackinator%20or%20BPP)/hacks/(UNSORTED%20DUMP)/SIM's%20labels%20suck%20in%20this%20-%20Puu_Black.xml) has silly placeholder labels. Some constants aren't even labeled at all. The entire thing should be relabeled.

**Comment by Brayconn** [comment]
It has been relabeled
