### ISSUE TITLE
Is "SlightlyInteligentMonkey - player_hitbox.xml" a duplicate or new version?

### ISSUE THREAD

**Issue by Enlight1** [CaveStoryModdingCommunity/FreewareHacks#5]
As far as I know, [SlightlyInteligentMonkey - player_hitbox.xml](https://github.com/CaveStoryModdingCommunity/FreewareHacks/blob/unsorted-dump/XML%20(BL%20Hackinator%20or%20BPP)/hacks/(UNSORTED%20DUMP)/SlightlyInteligentMonkey%20-%20player_hitbox.xml) is the latest version of the file uploaded to the CSMC's #resources channel, yet it is missing a bunch of the fields that are in the [years-older version](https://github.com/CaveStoryModdingCommunity/FreewareHacks/blob/main/XML%20(BL%20Hackinator%20or%20BPP)/hacks/player%20properties/player_rendersize_recoded.xml) (it seems to only concern itself with the hitbox and does not alter rendering?).

What's going on here? Someone will have to dig into both versions and figure out what should be used in the main directory.

**Comment by Brayconn** [comment]
player_hitbox has been moved into the obsolete folder
