### ISSUE TITLE
Falling block generator customizer

### ISSUE THREAD

**Issue by periwinkle9** [CaveStoryModdingCommunity/FreewareHacks#8]
Customizes almost every aspect of the falling block generator (NPC 294).
[NPC294.zip](https://github.com/CaveStoryModdingCommunity/FreewareHacks/files/8612268/NPC294.zip)

**Comment by Enlight1** [comment]
Added in commit [a5f87c5](https://github.com/CaveStoryModdingCommunity/FreewareHacks/commit/a5f87c5714496c5cc5512629180a8471e2ccafa1)
